# Generated by Django 2.0.4 on 2019-03-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdcommentdetail',
            name='commodityId',
            field=models.CharField(max_length=255),
        ),
    ]
